Added main.py, Makefile and tests
glebssha/regular-expression-parser pull request #1
Opened 2020-11-03 19:30 UTC by glebssha

2021-01-04 15:04 UTC, mizabrik requested changes
WA for `aa.* a`.

2021-01-04 15:04 UTC, mizabrik commented on main.py
> +Symbol = namedtuple('Symbol', ['Symbol', 'Type', 'LCloser', 'RCloser', 'LCounter', 'RCounter', 'Max'])
PEP8

2021-01-04 15:04 UTC, mizabrik commented on main.py
> +    stack = deque()
Почему не `list`?

2021-01-04 15:04 UTC, mizabrik commented on main.py
> +    list_cpy = copy(symbols_list)
Why?

2021-01-04 15:04 UTC, mizabrik commented on main.py
> +            list_cpy.pop(0)
Why?

2021-01-04 15:04 UTC, mizabrik commented on main.py
> +                    stack.append(multiply(last_sym, stack, list_cpy))
Why bother oneself passing `stack` and `list_cpy`?

2021-01-07 13:10 UTC, glebssha commented on main.py
> +    stack = deque()
Исправил

2021-01-07 13:11 UTC, glebssha commented on main.py
> +    list_cpy = copy(symbols_list)
Исправил

2021-01-07 13:11 UTC, glebssha commented on main.py
> +            list_cpy.pop(0)
Чтобы перейти к след символу, там находится сам автомат

2021-01-07 13:11 UTC, glebssha commented on main.py
> +                    stack.append(multiply(last_sym, stack, list_cpy))
В этих функциях я проверяю самый выгодный ответ, там и использую их

2021-03-31 16:06 UTC, merged